language: java
jdk:
  - openjdk11
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - ./gradlew clean build
  - ./gradlew jib

after_success:
  - bash <(curl -s https://codecov.io/bash)